# Import path to CSV's from Django settings
from mysite.settings import FOOTBALL_CSV_DIR
import pandas

# Read Football files
with open(FOOTBALL_CSV_DIR + 'matches_20.csv') as f:
    MATCH_DF = pandas.read_csv(f)
with open(FOOTBALL_CSV_DIR + 'players_20.csv') as f:
    FIFA_DF = pandas.read_csv(f)

# Uniform team names -- the team names in matches & players CSVs are not uniform
TEAM_NAMES = {
    # England
    'E10': "Arsenal",
    'E11': "Aston Villa",
    'E12': "Bournemouth",
    'E13': "Brighton",
    'E14': "Burnley",
    'E15': "Chelsea",
    'E16': "Crystal Palace",
    'E17': "Everton",
    'E18': "Leicester",
    'E19': "Liverpool",
    'E110': "Manchester City",
    'E111': "Manchester United",
    'E112': "Newcastle",
    'E113': "Norwich",
    'E114': "Sheffield United",
    'E115': "Southampton",
    'E116': "Tottenham",
    'E117': "Watford",
    'E118': "West Ham",
    'E119': "Wolves",
    # Germany
    'G10': "Augsburg",
    'G11': "Leverkusen",
    'G12': "Bayern",
    'G13': "Dortmund",
    'G14': "Borussia M'gladbach",
    'G15': "Frankfurt",
    'G16': "Köln",
    'G17': "Düsseldorf",
    'G18': "Freiburg",
    'G19': "Hertha",
    'G110': "Hoffenheim",
    'G111': "Mainz",
    'G112': "Paderborn",
    'G113': "Leipzig",
    'G114': "Schalke",
    'G115': "Union Berlin",
    'G116': "Werder Bremen",
    'G117': "Wolfsburg",
    # Italy
    'I10': "AC Milan",
    'I11': "Atalanta",
    'I12': "Bologna",
    'I13': "Brescia",
    'I14': "Cagliari",
    'I15': "Fiorentina",
    'I16': "Genoa",
    'I17': "Verona",
    'I18': "Inter Milan",
    'I19': "Juventus",
    'I110': "Lazio",
    'I111': "Lecce",
    'I112': "Napoli",
    'I113': "Parma",
    'I114': "Roma",
    'I115': "SPAL",
    'I116': "Sampdoria",
    'I117': "Sassuolo",
    'I118': "Torino",
    'I119': "Udinese",
    # Spain
    'S10': "Alavés",
    'S11': "Athletic Club",
    'S12': "Atlético Madrid",
    'S13': "Barcelona",
    'S14': "Celta Vigo",
    'S15': "Eibar",
    'S16': "Espanyol",
    'S17': "Getafe",
    'S18': "Granada",
    'S19': "Leganés",
    'S110': "Levante",
    'S111': "Mallorca",
    'S112': "Osasuna",
    'S113': "Real Betis",
    'S114': "Real Madrid",
    'S115': "Real Sociedad",
    'S116': "Sevilla",
    'S117': "Valencia",
    'S118': "Valladolid",
    'S119': "Villarreal",
    # France
    'F10': "Amiens",
    'F11': "Angers",
    'F12': "Bordeaux",
    'F13': "Brest",
    'F14': "Dijon",
    'F15': "Lille",
    'F16': "Lyon",
    'F17': "Marseille",
    'F18': "Metz",
    'F19': "Monaco",
    'F110': "Montpellier",
    'F111': "Nantes",
    'F112': "Nice",
    'F113': "Nîmes",
    'F114': "PSG",
    'F115': "Reims",
    'F116': "Rennes",
    'F117': "Saint-Étienne",
    'F118': "Strasbourg",
    'F119': "Toulouse"
}
